### ISSUE TITLE
How to modify ATAPortInjector.kext to match my motherboard?

### ISSUE THREAD

**Issue by HJebbour** [b00t0x/MSI-Z97M-Hackintosh-every-macOS#1]
Hi, could you share how did you achieve ATAPortInjector.kext patch for your motherboard? I have an HP computer with Haswell CPU and I managed to run all macOS except Tiger (due to AHCI issue as mentioned in your repo), and Snow Leopard it stuck at DSMOS has arrived, but that's another issue not related to AHCI.

**Comment by b00t0x** [comment]
@HJebbour see this.
https://github.com/b00t0x/MSI-Z97M-Hackintosh-every-macOS/blob/main/docs/install_en.md#tiger-104

Switch onboard SATA controller to IDE mode in the BIOS instead of AHCI mode. Then add [this](https://github.com/b00t0x/MSI-Z97M-Hackintosh-every-macOS/blob/main/EFI/OC/Kexts/ATAPortInjector.kext/Contents/Info.plist#L21-L41) patch. I'm using PCIe AHCI SSD for Leopard to Mavericks, but IDE mode + ATAPortInjector is compatible with [Tiger to Mojave](https://github.com/b00t0x/MSI-Z97M-Hackintosh-every-macOS/blob/main/docs/build_en.md#hcl).

**Comment by b00t0x** [comment]
And you must [block](https://github.com/b00t0x/MSI-Z97M-Hackintosh-every-macOS/blob/main/EFI/OC/config_noserial.plist#L689-L704) AHCI kext to avoid panic.

**Comment by HJebbour** [comment]
Thank you for your quick reply, I followed your steps exactly and used both your Info.plist and the one in Legacy Kexts but Mac OS X Tiger or others couldn't load with IDE mode, it stops at "Waiting for root device" which means it couldn't find the HDD. I saw that you said you modified the kext to work with your motherboard, that's why I want to know how did you find and make that modification.

**Comment by HJebbour** [comment]
I managed to boot Tiger from a flash USB with AHCI mode enabled in BIOS, but I had to "Disable" AppleAHCIPort in config.plist instead of "Exclude" so I think I will have Tiger installed in a flash USB drive and the rest of macOS on SSD drive with AHCI mode. But can I ask you which disk image you used for Snow Leopard?

**Comment by b00t0x** [comment]
@HJebbour 
> I want to know how did you find and make that modification.

Find IDE controller's device id with other version of macOS + Hackintool, then set it to `IOPCIPrimaryMatch` .
<br>

> But can I ask you which disk image you used for Snow Leopard?

OS X 10.6.7(10J4139) Acidanthera Image.

https://github.com/b00t0x/MSI-Z97M-Hackintosh-every-macOS/blob/main/docs/install_en.md#snow-leopard-106
> follow [OpenCore-Install-Guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install-dmg.html) to prepare the installer.

**Comment by HJebbour** [comment]
Thank you for your answer, I would like to let you know that if you copy the custom kernel to Mac OS X Tiger Install Disk you can boot from it and install it independently.
