### ISSUE TITLE
Hi,Bro

### ISSUE THREAD

**Issue by DankeBIBI** [b00t0x/MSI-Z97M-Hackintosh-every-macOS#2]
Hi， I am also using ROG G14 6800HS version. Sorry to bother you, but your other code repository has been closed. I wanted to ask you a question, so I'm here to leave a message, I downloaded a Mac 12.4 image package here and obtained three partitions using BalenaEtcher, one of which is OC. However, after copying the EFI of this repository and restarting, I don't know how to operate it. Can you teach me how to do it? thank you

**Comment by b00t0x** [comment]
It's a basic question about the Hackintosh, not about the G14. Follow the [guide](https://dortania.github.io/OpenCore-Install-Guide/).
